// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateCounter(ctx context.Context, arg CreateCounterParams) (Counter, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWidget(ctx context.Context, arg CreateWidgetParams) (Widget, error)
	DeleteCounter(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWidget(ctx context.Context, id int64) error
	GetCounter(ctx context.Context, id int64) (Counter, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetWidget(ctx context.Context, id int64) (Widget, error)
	ListCounters(ctx context.Context, arg ListCountersParams) ([]Counter, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWidgets(ctx context.Context, arg ListWidgetsParams) ([]Widget, error)
	UpdateCounter(ctx context.Context, arg UpdateCounterParams) (Counter, error)
	UpdateCounterValue(ctx context.Context, arg UpdateCounterValueParams) (Counter, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWidget(ctx context.Context, arg UpdateWidgetParams) (Widget, error)
}

var _ Querier = (*Queries)(nil)
